---
kind: pipeline
type: docker
name: production pipeline

clone:
  depth: 1

steps:
  - name: configure ssh
    image: plugins/ansible:3
    settings:
      galaxy: /drone/src/roles/requirements.yaml
      playbook: configure_ssh.yaml
      inventory: inventories/prod/hosts
      vault_password:
        from_secret: ansible_vault_password
    environment:
      SUPER_USER:
        from_secret: super_user
      SUPER_PASS:
        from_secret: super_pass

  # - name: deploy
  #   image: plugins/ansible:3
  #   settings:
  #     galaxy: /drone/src/roles/requirements.yaml
  #     playbook: deploy.yaml
  #     inventory: inventories/prod/hosts
  #     private_key:
  #       from_secret: ansible_private_key
  #     vault_password:
  #       from_secret: ansible_vault_password

  - name: docker_deploy
    image: plugins/ansible:3
    settings:
      galaxy: /drone/src/roles/requirements.yaml
      playbook: docker_deploy.yaml
      inventory: inventories/prod/hosts
      private_key:
        from_secret: ansible_private_key
      vault_password:
        from_secret: ansible_vault_password

trigger:
  branch:
    - development
  #   - stable
  # event:
  #   - tag
...
