---
kind: pipeline
type: docker
name: Install valheim Servers

clone:
  depth: 1

steps:

  - name: deploy (test servers)
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
    settings:
      playbook: .ansible/deploy.yaml
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventory/development
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password
    when:
      branch:
        - development
      event:
        - push

  - name: deploy (prod servers)
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
    settings:
      playbook: .ansible/deploy.yaml
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventory/production
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password
    when:
      branch:
        - stable
      event:
        - push

trigger:
  branch:
    - development
    - stable
  event:
    - push
...
