# ansible-playbook deploy.yaml -i inventories/prod/hosts --vault-id ~/.tokens/master_id

- hosts: all
  strategy: free
  tasks:

    - name: Create all the save directories
      file:
        path: '{{ directories_files }}/{{ server.name }}/saves'
        state: directory
        mode: '0755'
        owner: automation
        group: automation
      vars:
        server: '{{ item }}'
      with_items: '{{ servers }}'
      loop_control:
        label: '{{ directories_files }}/{{ item.name }}/saves'

    - name: Create all the server directories
      file:
        path: '{{ directories_files }}/{{ server.name }}/server'
        state: directory
        mode: '0755'
        owner: automation
        group: automation
      vars:
        server: '{{ item }}'
      with_items: '{{ servers }}'
      loop_control:
        label: '{{ directories_files }}/{{ item.name }}/server'

    - name: Render the admin lists
      template:
        src: list.txt.j2
        dest: '{{ directories_files }}/{{ item.name }}/saves/adminlist.txt'
      vars:
        players: '{{ item.admins }}'
      with_items: '{{ servers }}'
      loop_control:
        label: '{{ directories_files }}/{{ item.name }}/saves/adminlist.txt'

    - name: Render the banned lists
      template:
        src: list.txt.j2
        dest: '{{ directories_files }}/{{ item.name }}/saves/bannedlist.txt'
      vars:
        players: '{{ item.banned }}'
      with_items: '{{ servers }}'
      loop_control:
        label: '{{ directories_files }}/{{ item.name }}/saves/bannedlist.txt'

    - name: Render the permitted lists
      template:
        src: list.txt.j2
        dest: '{{ directories_files }}/{{ item.name }}/saves/permittedlist.txt'
      vars:
        players: '{{ item.permitted }}'
      with_items: '{{ servers }}'
      loop_control:
        label: '{{ directories_files }}/{{ item.name }}/saves/permittedlist.txt'

    - name: Render docker-compose.yaml & deploy stack
      import_role:
        name: docker-deploy

    - name: Allow server ports
      ufw:
        rule: allow
        port: "{{ server.port }}"
        proto: udp
      vars:
        server: '{{ item }}'
      with_items: '{{ servers }}'
      loop_control:
        label: '{{ item.port }}'
      become: yes

    - name: Allow server ports +1
      ufw:
        rule: allow
        port: "{{ server.port + 1 }}"
        proto: udp
      vars:
        server: '{{ item }}'
      with_items: '{{ servers }}'
      loop_control:
        label: '{{ item.port + 1 }}'
      become: yes

    - name: Allow server ports +2
      ufw:
        rule: allow
        port: "{{ server.port + 2 }}"
        proto: udp
      vars:
        server: '{{ item }}'
      with_items: '{{ servers }}'
      loop_control:
        label: '{{ item.port + 2 }}'
      become: yes

    - name: Reload Firewall and enable at boot
      ufw:
        state: enabled
        policy: deny
      become: yes


